In [2]:

import pandas as pd

df = pd.read_csv('gk_qna_dataset.csv')
df.head()

                            question  answer
0   What is the capital of "France"?   Paris
1  What is the capital of "Germany"?  Berlin
2    What is the capital of "Italy"?    Rome
3    What is the capital of "Spain"?  Madrid
4    What is the capital of "Japan"?   Tokyo

In [4]:
import re

def tokenize(text):
    # lowercase
    text = text.lower()
    # remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    # remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # remove quotes
    text = re.sub(r'[\'"]', '', text)
    tokens = text.split()
    
    return tokens
    

df['tokens'] = df['question'].apply(tokenize)
df.head()

,question,answer,tokens
0,what is the capital of france,paris,"[what, is, the, capital, of, france]"
1,what is the capital of germany,berlin,"[what, is, the, capital, of, germany]"
2,what is the capital of italy,rome,"[what, is, the, capital, of, italy]"
3,what is the capital of spain,madrid,"[what, is, the, capital, of, spain]"
4,what is the capital of japan,tokyo,"[what, is, the, capital, of, japan]"